from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.kingbillycasino.com/")
    page.get_by_role("button", name="accept").click()
    page.get_by_role("link", name="sign in").click()
    page.get_by_placeholder("your e-mail address").fill("s")
    page.get_by_role("button", name="").click()
    page.get_by_role("main").get_by_role("button", name="").first.click()
    page.get_by_role("link", name="New", exact=True).click()
    page.get_by_role("link", name="Top", exact=True).click()
    page.get_by_role("link", name="Popular").click()
    page.get_by_role("link", name="Jackpots", exact=True).click()
    page.get_by_role("link", name="Slots", exact=True).click()
    page.get_by_role("button", name="").first.click()
    page.get_by_role("link", name="Accumulating").click()
    page.get_by_role("button", name="").first.click()
    page.get_by_role("link", name="Bonus buy").click()
    page.get_by_role("button", name="").first.click()
    page.get_by_role("link", name="Megaways", exact=True).click()
    page.get_by_role("button", name="").first.click()
    page.get_by_role("link", name="Exclusive").click()
    page.get_by_role("button", name="").first.click()
    page.get_by_role("link", name="Crash").click()
    page.get_by_role("button", name="").first.click()
    page.get_by_role("link", name="Crash", exact=True).click()
    page.get_by_role("link", name="Live", exact=True).click()
    page.get_by_role("button", name="").first.click()
    page.get_by_role("link", name="Live blackjack").click()
    page.get_by_role("button", name="").first.click()
    page.get_by_role("link", name="Live roulette").click()
    page.get_by_role("button", name="").first.click()
    page.get_by_role("link", name="Live baccarat").click()
    page.get_by_role("button", name="").first.click()
    page.get_by_role("link", name="Live poker").click()
    page.get_by_role("link", name="Table games", exact=True).click()
    page.get_by_role("button", name="").click()
    page.get_by_role("link", name="Online roulette").click()
    page.get_by_role("button", name="").click()
    page.get_by_role("link", name="Online blackjack").click()
    page.get_by_role("button", name="").click()
    page.get_by_role("link", name="Online baccarat").click()
    page.get_by_role("link", name="Recent").click()
    page.get_by_role("link", name="Lobby").click()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
